FROM mcr.microsoft.com/dotnet/core/runtime:3.0-alpine3.10

#https://github.com/dotnet/dotnet-docker/blob/master/2.2/aspnet/alpine3.9/amd64/Dockerfile

# Install ASP.NET Core
ENV ASPNETCORE_VERSION 3.0.0
ENV DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=false

RUN apk update \
    && apk add ca-certificates wget \
    && update-ca-certificates
RUN apk add icu-libs

RUN wget -O aspnetcore.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/aspnetcore/Runtime/$ASPNETCORE_VERSION/aspnetcore-runtime-$ASPNETCORE_VERSION-linux-musl-x64.tar.gz \
    && aspnetcore_sha512='aa00899762a1593a12df9ae810aee54318dca603ca0aead51dd60fb23c459fda6f1ff6a331cc31a0c5d824d2d16afff5d1e6d5eb09776c3e542c431d03f50dfd' \
    && echo "$aspnetcore_sha512  aspnetcore.tar.gz" | sha512sum -c - \
    && tar -zxf aspnetcore.tar.gz -C /usr/share/dotnet ./shared/Microsoft.AspNetCore.App \
    && rm aspnetcore.tar.gz \
    && ln -fs /usr/share/dotnet/dotnet /usr/bin/dotnet

WORKDIR /app
ARG source
ENV ASPNETCORE_URLS http://+:80
EXPOSE 80
ARG environment
ENV ASPNETCORE_ENVIRONMENT=${environment}
COPY ${source:-/site} .
RUN ls -la
ENTRYPOINT ["dotnet", "enhancit.Merchant.Web.dll"]
