FROM keymetrics/pm2:latest-alpine

RUN apk update \
    && apk add ca-certificates wget \
    && update-ca-certificates

RUN apk add yarn

RUN apk add python2

RUN apk add make \
    && apk add g++ \
    && apk add gcc

RUN npm install pm2 -g && npm install node-gyp -g
ENV NPM_CONFIG_LOGLEVEL warn

RUN mkdir /var/www/ \
    && mkdir /var/www/enhancitnewsforo \
    && mkdir /var/www/enhancitnewsforo/src/

WORKDIR /var/www/enhancitnewsforo/
ARG source
ENV ASPNETCORE_URLS https://+:443
EXPOSE 443
COPY ${source:-/} .

RUN pwd

RUN npm install

RUN yarn build

RUN mkdir build/public/foro

RUN mv build/public/static/ build/public/foro/static

RUN ls -la

CMD ["pm2-runtime", "start", "ecosystem.config.js", "--name", "foro"]
